debug: false
server: 
  port: 8090
spring: 
  application:
    name: blog
  datasource:
    url: jdbc:mysql://10.110.1.26:3306/icp_bss?useUnicode=true&characterEncoding=UTF8&connectTimeout=10000&socketTimeout=100000&allowMultiQueries=true
    username:  bss_product
    password: bss_product_2019
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
#    active: prod
  redis:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
management:
  endpoints:
    web:
      base-path: /
      exposure:
        #        include: "*"
        include: prometheus


